<?xml version="1.0" encoding="utf-8"?><Database Name="nadhemni" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-F7MSF8V0;Initial Catalog=nadhemni;Integrated Security=True;Pooling=False" SettingsObjectName="Nadhemni_2020.Properties.Settings" SettingsPropertyName="nadhemniConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.adresse" Member="adresse">
    <Type Name="adresse">
      <Column Name="id_adresse" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rue" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="localisation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="adresse_identity" Member="identity" ThisKey="id_adresse" OtherKey="adresse" Type="identity" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="user">
    <Type Name="user">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mdp" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="user_identity" Member="identity" ThisKey="id_user" OtherKey="Id_personne" Type="identity" />
    </Type>
  </Table>
  <Table Name="dbo.[identity]" Member="identity">
    <Type Name="identity">
      <Column Name="Id_personne" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date_naissance" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="genre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="fonction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="adresse" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="etat_civil" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="nbre_enfant" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="etat_sante" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="etablissement" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="niveau_etude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="distance" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="adresse_identity" Member="adresse1" ThisKey="adresse" OtherKey="id_adresse" Type="adresse" IsForeignKey="true" />
      <Association Name="user_identity" Member="user" ThisKey="Id_personne" OtherKey="id_user" Type="user" IsForeignKey="true" />
      <Association Name="tache_identity" Member="tache" ThisKey="Id_personne" OtherKey="id_tache" Type="tache" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tache" Member="tache">
    <Type Name="tache">
      <Column Name="id_tache" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="t_debut" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="t_fin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="duree" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="emplacement" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="personne_imp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tache_identity" Member="identity" ThisKey="id_tache" OtherKey="Id_personne" Type="identity" />
    </Type>
  </Table>
</Database>