<?xml version="1.0" encoding="utf-8"?><Database Name="nadhemnidata" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-F7MSF8V0;Initial Catalog=nadhemnidata;Integrated Security=True;Pooling=False" SettingsObjectName="Nadhemni_2020.Properties.Settings" SettingsPropertyName="nadhemnidataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.adresse" Member="adresse">
    <Type Name="adresse">
      <Column Name="id_adresse" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numero" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rue" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="localisation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="id_persone" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="personne_adresse" Member="personne" ThisKey="id_persone" OtherKey="id_personne" Type="personne" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="user">
    <Type Name="user">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_pers" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pass" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="personne_user" Member="personne" ThisKey="id_pers" OtherKey="id_personne" Type="personne" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.personne" Member="personne">
    <Type Name="personne">
      <Column Name="id_personne" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date_de_naissance" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="genre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fonction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="etat_civil" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nbre_enfant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="etat_sante" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="etablissement" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="niveau_etude" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="distance" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="personne_adresse" Member="adresse" ThisKey="id_personne" OtherKey="id_persone" Type="adresse" />
      <Association Name="personne_user" Member="user" ThisKey="id_personne" OtherKey="id_pers" Type="user" />
      <Association Name="personne_plan" Member="plan" ThisKey="id_personne" OtherKey="id_prop" Type="plan" />
    </Type>
  </Table>
  <Table Name="dbo.[plan]" Member="plan">
    <Type Name="plan">
      <Column Name="id_taches" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_prop" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="date_heure_debut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="date_heure_fin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="accomplie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="personne_plan" Member="personne" ThisKey="id_prop" OtherKey="id_personne" Type="personne" IsForeignKey="true" />
      <Association Name="tache_plan" Member="tache" ThisKey="id_taches" OtherKey="id_tache" Type="tache" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tache" Member="tache">
    <Type Name="tache">
      <Column Name="id_tache" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="titre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="duree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="emplacement" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="personne_imp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="tache_plan" Member="plan" ThisKey="id_tache" OtherKey="id_taches" Type="plan" />
    </Type>
  </Table>
</Database>