#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nadhemni_2020
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nadhemnidata")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadresse(adresse instance);
    partial void Updateadresse(adresse instance);
    partial void Deleteadresse(adresse instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertpersonne(personne instance);
    partial void Updatepersonne(personne instance);
    partial void Deletepersonne(personne instance);
    partial void Insertplan(plan instance);
    partial void Updateplan(plan instance);
    partial void Deleteplan(plan instance);
    partial void Inserttache(tache instance);
    partial void Updatetache(tache instance);
    partial void Deletetache(tache instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Nadhemni_2020.Properties.Settings.Default.nadhemnidataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<adresse> adresse
		{
			get
			{
				return this.GetTable<adresse>();
			}
		}
		
		public System.Data.Linq.Table<user> user
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<personne> personne
		{
			get
			{
				return this.GetTable<personne>();
			}
		}
		
		public System.Data.Linq.Table<plan> plan
		{
			get
			{
				return this.GetTable<plan>();
			}
		}
		
		public System.Data.Linq.Table<tache> tache
		{
			get
			{
				return this.GetTable<tache>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.adresse")]
	public partial class adresse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_adresse;
		
		private string _numero;
		
		private string _rue;
		
		private string _localisation;
		
		private int _id_persone;
		
		private EntityRef<personne> _personne;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_adresseChanging(int value);
    partial void Onid_adresseChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    partial void OnrueChanging(string value);
    partial void OnrueChanged();
    partial void OnlocalisationChanging(string value);
    partial void OnlocalisationChanged();
    partial void Onid_personeChanging(int value);
    partial void Onid_personeChanged();
    #endregion
		
		public adresse()
		{
			this._personne = default(EntityRef<personne>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_adresse", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_adresse
		{
			get
			{
				return this._id_adresse;
			}
			set
			{
				if ((this._id_adresse != value))
				{
					this.Onid_adresseChanging(value);
					this.SendPropertyChanging();
					this._id_adresse = value;
					this.SendPropertyChanged("id_adresse");
					this.Onid_adresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(50)")]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rue", DbType="VarChar(50)")]
		public string rue
		{
			get
			{
				return this._rue;
			}
			set
			{
				if ((this._rue != value))
				{
					this.OnrueChanging(value);
					this.SendPropertyChanging();
					this._rue = value;
					this.SendPropertyChanged("rue");
					this.OnrueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_localisation", DbType="VarChar(50)")]
		public string localisation
		{
			get
			{
				return this._localisation;
			}
			set
			{
				if ((this._localisation != value))
				{
					this.OnlocalisationChanging(value);
					this.SendPropertyChanging();
					this._localisation = value;
					this.SendPropertyChanged("localisation");
					this.OnlocalisationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_persone", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_persone
		{
			get
			{
				return this._id_persone;
			}
			set
			{
				if ((this._id_persone != value))
				{
					if (this._personne.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_personeChanging(value);
					this.SendPropertyChanging();
					this._id_persone = value;
					this.SendPropertyChanged("id_persone");
					this.Onid_personeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_adresse", Storage="_personne", ThisKey="id_persone", OtherKey="id_personne", IsForeignKey=true)]
		public personne personne
		{
			get
			{
				return this._personne.Entity;
			}
			set
			{
				personne previousValue = this._personne.Entity;
				if (((previousValue != value) 
							|| (this._personne.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._personne.Entity = null;
						previousValue.adresse.Remove(this);
					}
					this._personne.Entity = value;
					if ((value != null))
					{
						value.adresse.Add(this);
						this._id_persone = value.id_personne;
					}
					else
					{
						this._id_persone = default(int);
					}
					this.SendPropertyChanged("personne");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private int _id_pers;
		
		private string _login;
		
		private string _pass;
		
		private EntityRef<personne> _personne;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void Onid_persChanging(int value);
    partial void Onid_persChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public user()
		{
			this._personne = default(EntityRef<personne>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pers", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pers
		{
			get
			{
				return this._id_pers;
			}
			set
			{
				if ((this._id_pers != value))
				{
					if (this._personne.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_persChanging(value);
					this.SendPropertyChanging();
					this._id_pers = value;
					this.SendPropertyChanged("id_pers");
					this.Onid_persChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="VarChar(50)")]
		public string login
		{
			get
			{
				return this._login;
			}
			set
			{
				if ((this._login != value))
				{
					this.OnloginChanging(value);
					this.SendPropertyChanging();
					this._login = value;
					this.SendPropertyChanged("login");
					this.OnloginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="VarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_user", Storage="_personne", ThisKey="id_pers", OtherKey="id_personne", IsForeignKey=true)]
		public personne personne
		{
			get
			{
				return this._personne.Entity;
			}
			set
			{
				personne previousValue = this._personne.Entity;
				if (((previousValue != value) 
							|| (this._personne.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._personne.Entity = null;
						previousValue.user.Remove(this);
					}
					this._personne.Entity = value;
					if ((value != null))
					{
						value.user.Add(this);
						this._id_pers = value.id_personne;
					}
					else
					{
						this._id_pers = default(int);
					}
					this.SendPropertyChanged("personne");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personne")]
	public partial class personne : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_personne;
		
		private string _nom;
		
		private string _prenom;
		
		private System.Nullable<System.DateTime> _date_de_naissance;
		
		private string _genre;
		
		private string _fonction;
		
		private System.Data.Linq.Binary _photo;
		
		private string _etat_civil;
		
		private System.Nullable<int> _nbre_enfant;
		
		private string _etat_sante;
		
		private string _etablissement;
		
		private string _niveau_etude;
		
		private string _distance;
		
		private string _mail;
		
		private EntitySet<adresse> _adresse;
		
		private EntitySet<user> _user;
		
		private EntitySet<plan> _plan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_personneChanging(int value);
    partial void Onid_personneChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void Ondate_de_naissanceChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_de_naissanceChanged();
    partial void OngenreChanging(string value);
    partial void OngenreChanged();
    partial void OnfonctionChanging(string value);
    partial void OnfonctionChanged();
    partial void OnphotoChanging(System.Data.Linq.Binary value);
    partial void OnphotoChanged();
    partial void Onetat_civilChanging(string value);
    partial void Onetat_civilChanged();
    partial void Onnbre_enfantChanging(System.Nullable<int> value);
    partial void Onnbre_enfantChanged();
    partial void Onetat_santeChanging(string value);
    partial void Onetat_santeChanged();
    partial void OnetablissementChanging(string value);
    partial void OnetablissementChanged();
    partial void Onniveau_etudeChanging(string value);
    partial void Onniveau_etudeChanged();
    partial void OndistanceChanging(string value);
    partial void OndistanceChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    #endregion
		
		public personne()
		{
			this._adresse = new EntitySet<adresse>(new Action<adresse>(this.attach_adresse), new Action<adresse>(this.detach_adresse));
			this._user = new EntitySet<user>(new Action<user>(this.attach_user), new Action<user>(this.detach_user));
			this._plan = new EntitySet<plan>(new Action<plan>(this.attach_plan), new Action<plan>(this.detach_plan));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_personne", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_personne
		{
			get
			{
				return this._id_personne;
			}
			set
			{
				if ((this._id_personne != value))
				{
					this.Onid_personneChanging(value);
					this.SendPropertyChanging();
					this._id_personne = value;
					this.SendPropertyChanged("id_personne");
					this.Onid_personneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_de_naissance", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_de_naissance
		{
			get
			{
				return this._date_de_naissance;
			}
			set
			{
				if ((this._date_de_naissance != value))
				{
					this.Ondate_de_naissanceChanging(value);
					this.SendPropertyChanging();
					this._date_de_naissance = value;
					this.SendPropertyChanged("date_de_naissance");
					this.Ondate_de_naissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genre", DbType="VarChar(50)")]
		public string genre
		{
			get
			{
				return this._genre;
			}
			set
			{
				if ((this._genre != value))
				{
					this.OngenreChanging(value);
					this.SendPropertyChanging();
					this._genre = value;
					this.SendPropertyChanged("genre");
					this.OngenreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fonction", DbType="VarChar(50)")]
		public string fonction
		{
			get
			{
				return this._fonction;
			}
			set
			{
				if ((this._fonction != value))
				{
					this.OnfonctionChanging(value);
					this.SendPropertyChanging();
					this._fonction = value;
					this.SendPropertyChanged("fonction");
					this.OnfonctionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etat_civil", DbType="VarChar(50)")]
		public string etat_civil
		{
			get
			{
				return this._etat_civil;
			}
			set
			{
				if ((this._etat_civil != value))
				{
					this.Onetat_civilChanging(value);
					this.SendPropertyChanging();
					this._etat_civil = value;
					this.SendPropertyChanged("etat_civil");
					this.Onetat_civilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbre_enfant", DbType="Int")]
		public System.Nullable<int> nbre_enfant
		{
			get
			{
				return this._nbre_enfant;
			}
			set
			{
				if ((this._nbre_enfant != value))
				{
					this.Onnbre_enfantChanging(value);
					this.SendPropertyChanging();
					this._nbre_enfant = value;
					this.SendPropertyChanged("nbre_enfant");
					this.Onnbre_enfantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etat_sante", DbType="VarChar(50)")]
		public string etat_sante
		{
			get
			{
				return this._etat_sante;
			}
			set
			{
				if ((this._etat_sante != value))
				{
					this.Onetat_santeChanging(value);
					this.SendPropertyChanging();
					this._etat_sante = value;
					this.SendPropertyChanged("etat_sante");
					this.Onetat_santeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etablissement", DbType="VarChar(50)")]
		public string etablissement
		{
			get
			{
				return this._etablissement;
			}
			set
			{
				if ((this._etablissement != value))
				{
					this.OnetablissementChanging(value);
					this.SendPropertyChanging();
					this._etablissement = value;
					this.SendPropertyChanged("etablissement");
					this.OnetablissementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau_etude", DbType="VarChar(50)")]
		public string niveau_etude
		{
			get
			{
				return this._niveau_etude;
			}
			set
			{
				if ((this._niveau_etude != value))
				{
					this.Onniveau_etudeChanging(value);
					this.SendPropertyChanging();
					this._niveau_etude = value;
					this.SendPropertyChanged("niveau_etude");
					this.Onniveau_etudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distance", DbType="VarChar(50)")]
		public string distance
		{
			get
			{
				return this._distance;
			}
			set
			{
				if ((this._distance != value))
				{
					this.OndistanceChanging(value);
					this.SendPropertyChanging();
					this._distance = value;
					this.SendPropertyChanged("distance");
					this.OndistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_adresse", Storage="_adresse", ThisKey="id_personne", OtherKey="id_persone")]
		public EntitySet<adresse> adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				this._adresse.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_user", Storage="_user", ThisKey="id_personne", OtherKey="id_pers")]
		public EntitySet<user> user
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_plan", Storage="_plan", ThisKey="id_personne", OtherKey="id_prop")]
		public EntitySet<plan> plan
		{
			get
			{
				return this._plan;
			}
			set
			{
				this._plan.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_adresse(adresse entity)
		{
			this.SendPropertyChanging();
			entity.personne = this;
		}
		
		private void detach_adresse(adresse entity)
		{
			this.SendPropertyChanging();
			entity.personne = null;
		}
		
		private void attach_user(user entity)
		{
			this.SendPropertyChanging();
			entity.personne = this;
		}
		
		private void detach_user(user entity)
		{
			this.SendPropertyChanging();
			entity.personne = null;
		}
		
		private void attach_plan(plan entity)
		{
			this.SendPropertyChanging();
			entity.personne = this;
		}
		
		private void detach_plan(plan entity)
		{
			this.SendPropertyChanging();
			entity.personne = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[plan]")]
	public partial class plan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_taches;
		
		private int _id_prop;
		
		private System.Nullable<System.DateTime> _date_heure_debut;
		
		private System.Nullable<System.DateTime> _date_heure_fin;
		
		private EntityRef<personne> _personne;
		
		private EntityRef<tache> _tache;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tachesChanging(int value);
    partial void Onid_tachesChanged();
    partial void Onid_propChanging(int value);
    partial void Onid_propChanged();
    partial void Ondate_heure_debutChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_heure_debutChanged();
    partial void Ondate_heure_finChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_heure_finChanged();
    #endregion
		
		public plan()
		{
			this._personne = default(EntityRef<personne>);
			this._tache = default(EntityRef<tache>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_taches", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_taches
		{
			get
			{
				return this._id_taches;
			}
			set
			{
				if ((this._id_taches != value))
				{
					if (this._tache.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tachesChanging(value);
					this.SendPropertyChanging();
					this._id_taches = value;
					this.SendPropertyChanged("id_taches");
					this.Onid_tachesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prop", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_prop
		{
			get
			{
				return this._id_prop;
			}
			set
			{
				if ((this._id_prop != value))
				{
					if (this._personne.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_propChanging(value);
					this.SendPropertyChanging();
					this._id_prop = value;
					this.SendPropertyChanged("id_prop");
					this.Onid_propChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_heure_debut", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_heure_debut
		{
			get
			{
				return this._date_heure_debut;
			}
			set
			{
				if ((this._date_heure_debut != value))
				{
					this.Ondate_heure_debutChanging(value);
					this.SendPropertyChanging();
					this._date_heure_debut = value;
					this.SendPropertyChanged("date_heure_debut");
					this.Ondate_heure_debutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_heure_fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_heure_fin
		{
			get
			{
				return this._date_heure_fin;
			}
			set
			{
				if ((this._date_heure_fin != value))
				{
					this.Ondate_heure_finChanging(value);
					this.SendPropertyChanging();
					this._date_heure_fin = value;
					this.SendPropertyChanged("date_heure_fin");
					this.Ondate_heure_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_plan", Storage="_personne", ThisKey="id_prop", OtherKey="id_personne", IsForeignKey=true)]
		public personne personne
		{
			get
			{
				return this._personne.Entity;
			}
			set
			{
				personne previousValue = this._personne.Entity;
				if (((previousValue != value) 
							|| (this._personne.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._personne.Entity = null;
						previousValue.plan.Remove(this);
					}
					this._personne.Entity = value;
					if ((value != null))
					{
						value.plan.Add(this);
						this._id_prop = value.id_personne;
					}
					else
					{
						this._id_prop = default(int);
					}
					this.SendPropertyChanged("personne");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tache_plan", Storage="_tache", ThisKey="id_taches", OtherKey="id_tache", IsForeignKey=true)]
		public tache tache
		{
			get
			{
				return this._tache.Entity;
			}
			set
			{
				tache previousValue = this._tache.Entity;
				if (((previousValue != value) 
							|| (this._tache.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tache.Entity = null;
						previousValue.plan.Remove(this);
					}
					this._tache.Entity = value;
					if ((value != null))
					{
						value.plan.Add(this);
						this._id_taches = value.id_tache;
					}
					else
					{
						this._id_taches = default(int);
					}
					this.SendPropertyChanged("tache");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tache")]
	public partial class tache : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tache;
		
		private string _titre;
		
		private string _description;
		
		private System.Nullable<int> _duree;
		
		private string _emplacement;
		
		private System.Nullable<int> _personne_imp;
		
		private string _type;
		
		private EntitySet<plan> _plan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tacheChanging(int value);
    partial void Onid_tacheChanged();
    partial void OntitreChanging(string value);
    partial void OntitreChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OndureeChanging(System.Nullable<int> value);
    partial void OndureeChanged();
    partial void OnemplacementChanging(string value);
    partial void OnemplacementChanged();
    partial void Onpersonne_impChanging(System.Nullable<int> value);
    partial void Onpersonne_impChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public tache()
		{
			this._plan = new EntitySet<plan>(new Action<plan>(this.attach_plan), new Action<plan>(this.detach_plan));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tache", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tache
		{
			get
			{
				return this._id_tache;
			}
			set
			{
				if ((this._id_tache != value))
				{
					this.Onid_tacheChanging(value);
					this.SendPropertyChanging();
					this._id_tache = value;
					this.SendPropertyChanged("id_tache");
					this.Onid_tacheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string titre
		{
			get
			{
				return this._titre;
			}
			set
			{
				if ((this._titre != value))
				{
					this.OntitreChanging(value);
					this.SendPropertyChanging();
					this._titre = value;
					this.SendPropertyChanged("titre");
					this.OntitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duree", DbType="Int")]
		public System.Nullable<int> duree
		{
			get
			{
				return this._duree;
			}
			set
			{
				if ((this._duree != value))
				{
					this.OndureeChanging(value);
					this.SendPropertyChanging();
					this._duree = value;
					this.SendPropertyChanged("duree");
					this.OndureeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emplacement", DbType="VarChar(50)")]
		public string emplacement
		{
			get
			{
				return this._emplacement;
			}
			set
			{
				if ((this._emplacement != value))
				{
					this.OnemplacementChanging(value);
					this.SendPropertyChanging();
					this._emplacement = value;
					this.SendPropertyChanged("emplacement");
					this.OnemplacementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personne_imp", DbType="Int")]
		public System.Nullable<int> personne_imp
		{
			get
			{
				return this._personne_imp;
			}
			set
			{
				if ((this._personne_imp != value))
				{
					this.Onpersonne_impChanging(value);
					this.SendPropertyChanging();
					this._personne_imp = value;
					this.SendPropertyChanged("personne_imp");
					this.Onpersonne_impChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tache_plan", Storage="_plan", ThisKey="id_tache", OtherKey="id_taches")]
		public EntitySet<plan> plan
		{
			get
			{
				return this._plan;
			}
			set
			{
				this._plan.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_plan(plan entity)
		{
			this.SendPropertyChanging();
			entity.tache = this;
		}
		
		private void detach_plan(plan entity)
		{
			this.SendPropertyChanging();
			entity.tache = null;
		}
	}
}
#pragma warning restore 1591
